export const styles = {
  container: {
    height: '70vh',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  header: {
    padding: '16px 24px',
    borderBottom: '1px solid #f0f0f0',
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  graphCard: {
    flex: 1,
    margin: '0 24px 24px 24px',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  graphContainer: {
    height: '56vh',
    minHeight: '200px',
    backgroundColor: '#f5f5f5',
    border: '1px solid #d9d9d9',
    borderRadius: '8px',
  },
  controls: {
    backgroundColor: '#fff',
    border: '1px solid #d9d9d9',
    borderRadius: '4px',
  },
  miniMap: {
    backgroundColor: '#fff',
    border: '1px solid #d9d9d9',
    borderRadius: '4px',
  },
  node: {
    background: '#fff',
    borderRadius: '8px',
    padding: '0',
    width: '280px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    overflow: 'hidden',
  },
  executionNode: {
    background: '#fff',
    border: '2px solid',
    borderRadius: '8px',
    padding: '0',
    width: '280px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    overflow: 'hidden',
    position: 'relative' as const,
  },
  nodeHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px',
    backgroundColor: '#e6f7ff',
    borderBottom: '1px solid #91d5ff',
  },
  nodeIndex: {
    width: '32px',
    height: '32px',
    borderRadius: '4px',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '700' as const,
    fontSize: '14px',
    flexShrink: 0,
  },
  nodeTitle: {
    fontWeight: '600' as const,
    fontSize: '15px',
    color: '#262626',
    lineHeight: '1.4',
  },
  nodeBody: {
    padding: '16px',
  },
  reasonLabel: {
    fontSize: '11px',
    color: '#8c8c8c',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    fontWeight: '600' as const,
    marginBottom: '8px',
  },
  nodeReason: {
    fontSize: '13px',
    color: '#595959',
    lineHeight: '1.6',
    fontStyle: 'italic' as const,
  },
  nodeFooter: {
    padding: '12px 16px',
    backgroundColor: '#fafafa',
    borderTop: '1px solid #f0f0f0',
  },
  nodeTool: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: '#1890ff',
    fontWeight: '600' as const,
  },
  toolIcon: {
    fontSize: '14px',
  },
  durationBadge: {
    position: 'absolute' as const,
    top: '8px',
    right: '8px',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    color: 'white',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    display: 'flex',
    alignItems: 'center',
  },
};
